package com.bank.bian.workforcetraining;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Workforce Training
 *
 * Business Area:      Business Support
 * Business Domain:    Human Resources
 * Functional Pattern: Operate
 * Asset Type:         Training Program
 * Control Record:     Training Program Operating Session
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Workforce Training — BIAN Semantic API")
                .description("Service Domain 'Workforce Training' (Operate pattern) "
                        + "operating on the 'Training Program Operating Session' control record.")
                .version("0.1.0"));
    }
}
